# NN module

In [10]:
import torch
import torch.nn as nn

In [11]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,x):
        z = self.linear(x)
        y_pred = self.sigmoid(z)
        return y_pred

In [12]:
features = torch.randn(10,5)

model = Model(features.shape[1])

model(features)


tensor([[0.6203],
        [0.3487],
        [0.5501],
        [0.4623],
        [0.3487],
        [0.3761],
        [0.3671],
        [0.5483],
        [0.5987],
        [0.4894]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear.weight
model.linear.bias

Parameter containing:
tensor([-0.1781], requires_grad=True)

In [14]:
!pip install torchinfo

In [15]:
from torchinfo import summary

In [16]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Making hidden layer NN using sequentail 

In [27]:
class HiddenLayerModel(nn.Module):
    def __init__(self,x):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(x.shape[1],3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self,x):
       
        y_pred = self.network(x)
        return y_pred

In [19]:
model = HiddenLayerModel(features)

In [20]:
model(features)

tensor([[0.3577],
        [0.3752],
        [0.3918],
        [0.3635],
        [0.3971],
        [0.4016],
        [0.4310],
        [0.3850],
        [0.4066],
        [0.3898]], grad_fn=<SigmoidBackward0>)

In [25]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
HiddenLayerModel                         [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00